"""Pick reference-voice clips from a LibriTTS-R subset (CC BY 4.0, OpenSLR 141).

Reads the downloaded archive directly (no need to extract 1.3 GB) or an
extracted folder, finds each speaker's best single utterance for voice cloning,
and copies it out with its exact transcript.

  # 1. audition: best clips per speaker -> output/voice_audition/
  python tools/pick_libritts_voices.py audition  D:/Downloads/dev_clean.tar.gz

  # 2. export the ones you liked into Voices/, padded with 0.5 s / 0.3 s of silence
  #    (+ Voices/voices.json, Voices/ATTRIBUTION.md); --no-pad copies them as-is
  python tools/pick_libritts_voices.py export D:/Downloads/dev_clean.tar.gz \
        3752_4944_000016_000001=narrator_m1 84_121123_000008_000000=narrator_f1

A "best" clip is one utterance of 8-15 s (target 11 s), not clipped, reasonably
loud, short leading/trailing silence, and a transcript that is a plain
sentence (ends in . ! ?, no quotes/brackets, no stray digits).
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import math
import re
import shutil
import sys
import tarfile
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
AUDITION_DIR = ROOT / "output" / "voice_audition"
VOICES_DIR = ROOT / "Voices"

MIN_S, MAX_S, TARGET_S = 8.0, 15.0, 11.0
PER_SPEAKER = 3

ATTRIBUTION = """\
# Bundled reference voices

The voices in the table below are single utterances from **LibriTTS-R**
(Koizumi et al., 2023), licensed under
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Each file is named
after its LibriTTS-R utterance ID, or after a label chosen at export; the
table maps every file to its utterance. A clip's transcript is its `ref_text`
in `voices.json`, or the `.original.txt` / `.normalized.txt` file beside it.

**Changes:** silence was added at the start and end of the clips, as the
table lists. This avoids a breath or blip at the start of generated speech.
The audio is otherwise unmodified. `docs/samples/clone_original.mp3` is the
original recording of `8297_275155_000003_000001`, converted to MP3; the other
files in `docs/samples/` were generated by this project from these clips.

- Corpus: https://www.openslr.org/141/
- Paper: Y. Koizumi, H. Zen, S. Karita, Y. Ding, K. Yatabe, N. Morioka,
  M. Bacchiani, Y. Zhang, W. Han, A. Bapna. "LibriTTS-R: A Restored
  Multi-Speaker Text-to-Speech Corpus." Interspeech 2023. arXiv:2305.18802
- LibriTTS-R is derived from LibriTTS (Zen et al., 2019, CC BY 4.0), which is
  derived from LibriSpeech and the public-domain audiobooks of
  [LibriVox](https://librivox.org/). Thanks to the LibriVox volunteer readers.

| File | Alias | LibriTTS-R utterance | Reader | Gender | Changes |
|---|---|---|---|---|---|
"""
LEAD_S, TAIL_S = 0.5, 0.3      # silence added on export (README: "Breath or blip at the start of the output")


def write_attribution(voices_dir: Path, meta: dict) -> Path:
    """(Re)write Voices/ATTRIBUTION.md from every LibriTTS-R entry in voices.json."""
    lines = [ATTRIBUTION]
    for fn, m in sorted(meta.items()):
        if m.get("source") == "LibriTTS-R":
            lines.append(f"| `{fn}` | {m.get('alias') or '-'} | `{m['utterance']}` | {m['speaker']} | "
                         f"{m.get('gender', '?')} | {m.get('changes') or 'none'} |\n")
    out = voices_dir / "ATTRIBUTION.md"
    out.write_text("".join(lines), encoding="utf-8")
    return out


def _pad(wav: bytes, lead: float, tail: float) -> bytes:
    """Add digital silence to both ends of a PCM wav, keeping its format."""
    with wave.open(io.BytesIO(wav)) as r:
        params, frames = r.getparams(), r.readframes(r.getnframes())
    width = params.sampwidth * params.nchannels
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setparams(params)
        w.writeframes(bytes(int(lead * params.framerate) * width) + frames
                      + bytes(int(tail * params.framerate) * width))
    return buf.getvalue()


# ------------------------------------------------------------------ reading
class Source:
    """Uniform access to a .tar.gz or an extracted LibriTTS-R folder."""

    def __init__(self, path: Path):
        self.path = path
        self.is_tar = path.is_file()

    def walk(self):
        """Yield (relative_name, bytes) for every .wav / .txt / speakers file."""
        if self.is_tar:
            with tarfile.open(self.path, "r|gz") as tf:          # streaming: one pass
                for m in tf:
                    if m.isfile() and _wanted(m.name):
                        yield m.name, tf.extractfile(m).read()
        else:
            for p in sorted(self.path.rglob("*")):
                if p.is_file() and _wanted(p.name):
                    yield p.relative_to(self.path).as_posix(), p.read_bytes()

    def fetch(self, utt_ids: set[str]) -> dict[str, bytes]:
        out = {}
        for name, data in self.walk():
            stem = Path(name).name
            if stem.endswith(".wav") and stem[:-4] in utt_ids:
                out[stem[:-4]] = data
                if len(out) == len(utt_ids):
                    break
        return out


def _wanted(name: str) -> bool:
    n = Path(name).name
    return n.endswith((".wav", ".normalized.txt")) or n.lower() in {"speakers.tsv", "speakers.txt"}


def _parse_speakers(data: bytes) -> dict[str, tuple[str, str]]:
    """speakers.tsv (READER GENDER SUBSET NAME) or SPEAKERS.TXT (ID | SEX | ...)."""
    out = {}
    for line in data.decode("utf-8", "replace").splitlines():
        if not line.strip() or line.startswith((";", "READER")):
            continue
        parts = [p.strip() for p in (line.split("|") if "|" in line else line.split("\t"))]
        if len(parts) >= 2 and parts[0].isdigit():
            out[parts[0]] = (parts[1].upper()[:1], parts[-1] if len(parts) >= 4 else "")
    return out


def _wav_stats(data: bytes) -> dict | None:
    try:
        with wave.open(io.BytesIO(data)) as w:
            sr, ch, sw, n = w.getframerate(), w.getnchannels(), w.getsampwidth(), w.getnframes()
            dur = n / sr if sr else 0.0
            if sw != 2 or ch != 1 or not (MIN_S <= dur <= MAX_S):
                return {"sr": sr, "dur": dur, "ok": False}      # header only: skip decoding
            s = np.frombuffer(w.readframes(n), dtype="<i2").astype(np.int32)
    except Exception:
        return None
    a = np.abs(s)
    rms = float(np.sqrt(np.mean((s[::4].astype(np.float64)) ** 2)))
    # leading / trailing silence: first/last 10 ms window louder than -40 dBFS
    win = sr // 100
    loud = np.flatnonzero(a[: len(a) // win * win].reshape(-1, win).max(axis=1) > 327)
    nwin = len(a) // win
    lead = loud[0] * win / sr if len(loud) else dur
    trail = (nwin - 1 - loud[-1]) * win / sr if len(loud) else dur
    return {"sr": sr, "dur": dur, "ok": True, "peak": int(a.max()),
            "clipped": int(np.count_nonzero(a >= 32700)),
            "rms_db": 20 * math.log10(max(rms, 1.0) / 32768), "lead": lead, "trail": trail}


def load_speakers(path: Path | None) -> dict[str, tuple[str, str]]:
    """Speaker genders from doc.tar.gz / another archive / a speakers.tsv file."""
    if not path:
        return {}
    if path.suffix.lower() in {".tsv", ".txt"}:
        return _parse_speakers(path.read_bytes())
    out = {}
    for name, data in Source(path).walk():
        if Path(name).name.lower() in {"speakers.tsv", "speakers.txt"}:
            out.update(_parse_speakers(data))
    return out


BAD_TEXT = re.compile(r"[\"“”‘’()\[\]{}_*#/\\0-9]|--|;")


def _score(st: dict, text: str) -> float | None:
    if not st or not st.get("ok") or not (MIN_S <= st["dur"] <= MAX_S):
        return None
    if st["clipped"] > 5 or st["rms_db"] < -32 or BAD_TEXT.search(text) or not text.rstrip().endswith((".", "!", "?")):
        return None
    if len(text.split()) < 12:                          # too sparse for the duration: long pauses
        return None
    return (abs(st["dur"] - TARGET_S)                   # closer to 11 s is better
            + 4 * max(0, st["lead"] - 0.4) + 4 * max(0, st["trail"] - 0.5)
            + 0.05 * abs(st["rms_db"] + 22))            # prefer ~-22 dBFS


def index(src: Source):
    speakers, texts, stats = {}, {}, {}
    for name, data in src.walk():
        base = Path(name).name
        if base.lower() in {"speakers.tsv", "speakers.txt"}:
            speakers.update(_parse_speakers(data))
        elif base.endswith(".normalized.txt"):
            texts[base[: -len(".normalized.txt")]] = data.decode("utf-8", "replace").strip()
        elif base.endswith(".wav"):
            stats[base[:-4]] = _wav_stats(data)
    return speakers, texts, stats


# ------------------------------------------------------------------ commands
def cmd_audition(src: Source, per_speaker: int, out: Path, extra_speakers: dict):
    print(f"Indexing {src.path} (one pass) ...", flush=True)
    speakers, texts, stats = index(src)
    speakers = {**extra_speakers, **speakers}
    by_spk: dict[str, list] = {}
    for utt, st in stats.items():
        sc = _score(st, texts.get(utt, ""))
        if sc is not None:
            by_spk.setdefault(utt.split("_")[0], []).append((sc, utt))
    picks = {spk: [u for _, u in sorted(c)[:per_speaker]] for spk, c in by_spk.items()}
    all_spk = sorted({u.split("_")[0] for u in stats}, key=int)
    print(f"{len(stats)} utterances, {len(all_spk)} speakers, {sum(map(len, picks.values()))} candidates")

    wanted = {u for us in picks.values() for u in us}
    blobs = src.fetch(wanted)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    rows = []
    for spk in all_spk:
        g, name = speakers.get(spk, ("?", ""))
        for rank, utt in enumerate(picks.get(spk, []), 1):
            st = stats[utt]
            fn = f"{g if g in 'FM' else 'X'}_{spk}_{rank}_{st['dur']:.1f}s.wav"
            (out / fn).write_bytes(blobs[utt])
            rows.append({"file": fn, "utt": utt, "speaker": spk, "gender": g, "reader": name,
                         "dur_s": round(st["dur"], 1), "rms_db": round(st["rms_db"], 1), "text": texts[utt]})
        if spk not in picks:
            print(f"  speaker {spk} ({g}): no clip passed the filters")
    with open(out / "candidates.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {len(rows)} clips + candidates.csv to {out}")
    print("Files are named <gender>_<speaker>_<rank>_<seconds>.wav -- listen, then run `export`.")


def cmd_export(src: Source, mapping: list[str], voices_dir: Path, extra_speakers: dict, pad: bool = True):
    pairs = {}
    for m in mapping:
        utt, _, label = m.partition("=")
        if not label or not re.fullmatch(r"[A-Za-z0-9_\-]+", label):
            sys.exit(f"bad mapping {m!r}: expected <utterance_id>=<label>")
        pairs[utt] = label
    print(f"Reading {src.path} ...", flush=True)
    speakers, texts, blobs = dict(extra_speakers), {}, {}
    for name, data in src.walk():
        base = Path(name).name
        if base.lower() in {"speakers.tsv", "speakers.txt"}:
            speakers.update(_parse_speakers(data))
        elif base.endswith(".normalized.txt") and base[: -len(".normalized.txt")] in pairs:
            texts[base[: -len(".normalized.txt")]] = data.decode("utf-8", "replace").strip()
        elif base.endswith(".wav") and base[:-4] in pairs:
            blobs[base[:-4]] = data
    missing = set(pairs) - set(blobs)
    if missing:
        sys.exit(f"not found in archive: {', '.join(sorted(missing))}")

    meta_path = voices_dir / "voices.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.is_file() else {}
    for utt, label in pairs.items():
        spk = utt.split("_")[0]
        fn = f"{label}.wav"
        (voices_dir / fn).write_bytes(_pad(blobs[utt], LEAD_S, TAIL_S) if pad else blobs[utt])
        meta[fn] = {"display": label.replace("_", " "), "ref_text": texts[utt], "language": "English",
                    "source": "LibriTTS-R", "utterance": utt, "speaker": spk,
                    "gender": speakers.get(spk, ("?", ""))[0], "license": "CC BY 4.0",
                    "changes": (f"added {LEAD_S} s of silence at the start and {TAIL_S} s at the end; renamed"
                                if pad else "renamed")}
        print(f"  {fn:<24} <- {utt}")
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Updated {meta_path} and {write_attribution(voices_dir, meta)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--speakers", type=Path, help="doc.tar.gz or speakers.tsv, if the subset archive lacks one")
    a = sub.add_parser("audition", parents=[common])
    a.add_argument("source", type=Path)
    a.add_argument("--per-speaker", type=int, default=PER_SPEAKER)
    a.add_argument("--out", type=Path, default=AUDITION_DIR)
    e = sub.add_parser("export", parents=[common])
    e.add_argument("source", type=Path)
    e.add_argument("mapping", nargs="+", help="<utterance_id>=<label>")
    e.add_argument("--voices-dir", type=Path, default=VOICES_DIR)
    e.add_argument("--no-pad", action="store_true",
                   help=f"copy clips as-is (default: add {LEAD_S} s / {TAIL_S} s of silence)")
    args = ap.parse_args()
    src = Source(args.source)
    if not args.source.exists():
        sys.exit(f"{args.source} not found")
    extra = load_speakers(args.speakers)
    if args.cmd == "audition":
        cmd_audition(src, args.per_speaker, args.out, extra)
    else:
        cmd_export(src, args.mapping, args.voices_dir, extra, pad=not args.no_pad)


if __name__ == "__main__":
    main()
